title: Scenius Infra Upgrade
description: Planning shared community tools and communication infrastructure for the Sensemaking Scenius

collections:
  sessions:
    output: true
    sort_by: date
    order: reverse
  workshops:
    output: true
    sort_by: date
    order: reverse
  artifacts:
    output: true
    sort_by: date
    order: reverse

defaults:
  - scope:
      path: ""
      type: sessions
    values:
      layout: session
  - scope:
      path: ""
      type: workshops
    values:
      layout: workshop
  - scope:
      path: ""
      type: artifacts
    values:
      layout: artifact
