title: Scenius Infra Upgrade
description: A community of practice for a regen, intentional, & meaningful internet

collections:
  sessions:
    output: true
    sort_by: date
    order: reverse
  workshops:
    output: true
    sort_by: date
    order: reverse

defaults:
  - scope:
      path: ""
      type: sessions
    values:
      layout: session
  - scope:
      path: ""
      type: workshops
    values:
      layout: workshop
